version: '3.2'
services:
  backend1:
    image: crccheck/hello-world
  backend2:
    image: crccheck/hello-world
  backend3:
    image: crccheck/hello-world
  loadbalancer:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    links:
      - backend1
      - backend2
    ports:
      - "8765:80"
